---
os: linux
dist: xenial

language: python
python:
  - "3.6"

install:
  - |
    pip3 install -r requirements.txt && \
    pip3 install -r test_requirements.txt
script:
  - |
    yapf --quiet --style "{based_on_style: pep8, blank_line_before_nested_class_or_def: true, indent_dictionary_value: true, dedent_closing_brackets: true, column_limit: 99}" --recursive .
  - flake8 .
  - mypy rxn_onmt_utils

deploy:
  provider: pypi
  server: https://${PYPI_SERVER}
  distributions: "sdist bdist_wheel"
  username: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true

